AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  testHelloWorld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.huirongxing.serverless.ci.Sample::greeting
      Runtime: java8
      CodeUri:
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::662888367025:role/service-role/testHelloWorld'
      Events:
        TestHelloWorld:
          Type: Api
          Properties:
            Path: /testHelloWorld
            Method: ANY