version 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  build:
    commands:
      - echo build started on `date`
      - gradle jacocoTestReport build
  post_build:
    commands:
      - echo Build completed on `data`
artifacts:
  files:
    - build/libs/hello-world-1.0-SNAPSHOT.jar
    - build/reports/**/*